site_name: condor_tensorflow
site_url: http://GarrettJenkinson.github.io/condor_tensorflow
site_author: Garrett Jenkinson
site_description: condor_tensorflow is a package implementing the CONDOR tensorflow utilities.

repo_url: https://github.com/GarrettJenkinson/condor_tensorflow

#include_search: true
#theme: yeti

docs_dir: docs

theme: readthedocs

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True # for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2021 <a href="http://github.com/GarrettJenkinson">Garrett Jenkinson</a>

nav:
    - Home: index.md
    - Tutorials:
      - Poker Hands: tutorials/poker.md
    - Installation: installation.md
    - Changelog: CHANGELOG.md
    - Citing: citing.md
    - License: license.md
    - API:
          - condor_tensorflow.loss: api_subpackages/condor_tensorflow.loss.md
          - condor_tensorflow.metrics: api_subpackages/condor_tensorflow.metrics.md
          - condor_tensorflow.activations: api_subpackages/condor_tensorflow.activations.md
          - condor_tensorflow.labelencoder: api_subpackages/condor_tensorflow.labelencoder.md
          - condor_tensorflow.labelencoder.BaseEstimator: api_modules/condor_tensorflow.labelencoder/BaseEstimator.md
          - condor_tensorflow.labelencoder.CondorOrdinalEncoder: api_modules/condor_tensorflow.labelencoder/CondorOrdinalEncoder.md
          - condor_tensorflow.labelencoder.OrdinalEncoder: api_modules/condor_tensorflow.labelencoder/OrdinalEncoder.md
          - condor_tensorflow.labelencoder.TransformerMixin: api_modules/condor_tensorflow.labelencoder/TransformerMixin.md
          - condor_tensorflow.loss.CondorOrdinalCrossEntropy: api_modules/condor_tensorflow.loss/CondorOrdinalCrossEntropy.md
          - condor_tensorflow.loss.SparseCondorOrdinalCrossEntropy: api_modules/condor_tensorflow.loss/SparseCondorOrdinalCrossEntropy.md
          - condor_tensorflow.metrics.OrdinalEarthMoversDistance: api_modules/condor_tensorflow.metrics/OrdinalEarthMoversDistance.md
          - condor_tensorflow.metrics.OrdinalMeanAbsoluteError: api_modules/condor_tensorflow.metrics/OrdinalMeanAbsoluteError.md
          - condor_tensorflow.metrics.SparseOrdinalEarthMoversDistance: api_modules/condor_tensorflow.metrics/SparseOrdinalEarthMoversDistance.md
          - condor_tensorflow.metrics.SparseOrdinalMeanAbsoluteError: api_modules/condor_tensorflow.metrics/SparseOrdinalMeanAbsoluteError.md
